; [env:esp32-s3-devkitc-1]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino

; monitor_speed = 115200

; lib_deps = 
;     marcoschwartz/LiquidCrystal_I2C@^1.1.4
;     adafruit/RTClib
;     paulstoffregen/OneWire@^2.3.7
;     milesburton/DallasTemperature@^3.11.0
;     ; No WiFi, no WebServer, no ArduinoJson, no DHT (we use DS18B20)



[env:esp32-s3-devkitc-1]

platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

board = esp32-s3-devkitc-1

framework = arduino

monitor_speed = 115200

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/RTClib
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0

build_flags =
-D ARDUINO_USB_CDC_ON_BOOT=1